description: "A life worth sharing"
masthead_title: false
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

minimal_mistakes_skin: default

masthead_title: ""
title: " "

author:
  name: "ਭਾਈ ਇੰਦਰਜੀਤ ਸਿੰਘ ਜੀ"
  avatar: "/images/Dad_Pic.jpg"
  bio: "A Life of Kirtan, Seva, and Devotion"

defaults:
- scope:
    path: ""
  values:
    author_profile: true
defaults:
  - scope:
      path: ""
    values:
      author_profile: true

  - scope:
      path: ""
      type: "pages"
    values:
      sidebar:
        position: left

search: true
